name: Generate package-lock.json
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Commit package-lock.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package-lock.json
          git commit -m "Regenerate package-lock.json"
          git push
      - name: Upload npm log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-log
          path: /home/runner/.npm/_logs/*.log
